require "user.plugins"
require "user.cmp"
require "user.debug"
-- require "format"
require "user.general"
require "user.keymaps"
require "user.lsp"
require "user.project"
require "user.projectionist"
require "user.telescope"
-- require "user.theme"
require "user.treesitter"
